name: Publish Docker Image

on:
  push:
    branches: ["master"]

env:
  REPO_USER: irfanfadilah
  REPO_NAME: markitdown

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.REPO_USER }} --password-stdin

      - name: Build Docker Image
        run: docker build --tag ghcr.io/${{ env.REPO_USER }}/${{ env.REPO_NAME }}:latest --label service=${{ env.REPO_NAME }} .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ env.REPO_USER }}/${{ env.REPO_NAME }}:latest

  clean-up:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      packages: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clean Up
        run: |
          HEADER="Accept: application/vnd.github.v3+json"
          ENDPOINT="https://api.github.com/users/${{ env.REPO_USER }}/packages/container/${{ env.REPO_NAME }}/versions"

          images=$(gh api -H "$HEADER" $ENDPOINT | jq -r '.[] | select(.metadata.container.tags[0] != "latest") | .id')

          for image in $images; do
            gh api -X DELETE -H "$HEADER" $ENDPOINT/$image
          done
